import type { NextPage } from 'next'
import Head from 'next/head'
import { Player } from 'src/components/Player'
import { ICardType } from 'src/types'
import { useStore } from 'src/store'
import { useMount } from 'ahooks'

const Home: NextPage = () => {
  const init = useStore((store) => store.init)
  const players = useStore((store) => store.players)
  const addCard = useStore((store) => store.addCard)

  useMount(init)

  const onClickAddCard = (type: ICardType) => {
    addCard(type)
  }

  return (
    <div className={'h-screen bg-gray-100'}>
      <Head>
        <title>Catan with Friends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'p-6 flex flex-col gap-4'}>
        {players.map((player) => (
          <Player key={player.id} player={player} />
        ))}

        <button onClick={() => onClickAddCard('BRICK')}>Add BRICK</button>
      </main>
    </div>
  )
}

export default Home
