name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - do-not-build
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CATAN_WITH_FRIENDS }}'
          channelId: live
          projectId: catan-with-friends
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
